export const SWITCH_BRANCH = "SWITCH_BRANCH";
export const UPDATE_RELATION_GRAPH = "UPDATE_RELATION_GRAPH";
export const UPDATE_SELECTED_PATH = "UPDATE_SELECT_PATH";
export const UPDATE_ENTITY_TYPE_FILTER = "UPDATE_ENTITY_TYPE_FILTER";
export const TOGGLE_SHOW_DIFF = "TOGGLE_SHOW_DIFF";
export const UPDATE_DIFF = "UPDATE_DIFF";
